name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Sostituisci 'main' con il nome del tuo branch se necessario
      - gh-pages
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # Configura l'identità Git
      - name: Configure Git
        run: |
          git config --global user.name "mattia.giannetti"
          git config --global user.email "mattiagiannetti@atiproject.com"

      # Esegui il deploy
      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
